label linux
  kernel /boot/Image
  # See extlinux-a.conf for why the device tree is named explicitly.
  fdt /boot/sun50i-h700-anbernic-rg40xx-v.dtb
  # See extlinux-a.conf for why console=tty0 and loglevel=5 are here and
  # "quiet" is not.
  append console=ttyS0,115200 console=tty0 root=/dev/mmcblk0p3 rootfstype=squashfs rootwait loglevel=5
